echo "Manish Bharti"
echo "1947235"
echo
echo "1.Demonstrate the commands to change the ownership of a file"
echo "2.Demonstrate the commands to change the group of user."
echo "3.Demonstrate the recursive option to assign file permission"
echo "4.Create a shell script (Permission.sh) to assign the file privileges at the time of creating a file based on  roles"
echo "5.Write a shell script to group and compress the file based on their file extension"
echo "6.Write a shell script to archive the files which are not accessed for past three months"
echo "7.Create a compressed file called Collection.tar and move all the files starting with a specific character to the directory collection.tar"
echo "8.Compress the files from the current directory which consume more than 1GB"
echo "9.Group and compress the files based on their file permission.(For example compress the file with ‘read’ only/’re>echo "Enter your option"
read option"
